# RF2O is needed only when no other odometry source publishes odom -> base_footprint.
laser_scan_topic: /scan
odom_topic: /odom
publish_tf: true
base_frame_id: base_footprint
odom_frame_id: odom
init_pose_from_topic: ""
freq: 10.0
verbose: false

